version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: DevConnect.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: devconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vue:
    image: node:18
    working_dir: /app
    volumes:
      - ./devconnect-web:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  phpmyadmin:
    image: adminer  # Use Adminer instead of phpMyAdmin for PostgreSQL
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
